use_frameworks!

platform :ios, '8.0'

target 'SYZNavigationControllerKit_Example' do
  pod 'SYZNavigationControllerKit', :path => '../'

  target 'SYZNavigationControllerKit_Tests' do
    inherit! :search_paths

  end
end
